export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';
export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const FETCH_TWEETS_REQUEST = 'FETCH_TWEETS_REQUEST';
export const FETCH_TWEETS_SUCCESS = 'FETCH_TWEETS_SUCCESS';
export const FETCH_TWEETS_FAILURE = 'FETCH_TWEETS_FAILURE';
export const FETCH_PRIMARY_TWEETS_REQUEST = 'FETCH_PRIMARY_TWEETS_REQUEST';
export const FETCH_PRIMARY_TWEETS_SUCCESS = 'FETCH_PRIMARY_TWEETS_SUCCESS';
export const FETCH_PRIMARY_TWEETS_FAILURE = 'FETCH_PRIMARY_TWEETS_FAILURE';

export const SAVE_TWEET_REQUEST = 'SAVE_TWEET_REQUEST';
export const SAVE_TWEET_SUCCESS = 'SAVE_TWEET_SUCCESS';
export const SAVE_TWEET_FAILURE = 'SAVE_TWEET_FAILURE';

export const LOCAL_TWEET_UPDATE = 'LOCAL_TWEET_UPDATE';
export const RESET = 'RESET';

export const CLEAR_SERVER_ERRORS = 'CLEAR_SERVER_ERRORS';
